# Generated by Django 5.1.6 on 2025-02-06 04:31

from django.db import migrations, models

def make_products(app, *args, **kwargs):
    Product = app.get_model('products', 'Product')
    Product.objects.create(name='Product 1', description='Description')
    Product.objects.create(name='Product 2', description='Description', price=10, stock=1)
    Product.objects.create(name='Product 3', description='Description', price=100, stock=10)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(
            make_products
        ),
    ]
